@BASE_URL = http://127.0.0.1:8000/category

# Get All Category
GET {{BASE_URL}}
###

# Get Category By Id
GET {{BASE_URL}}/id/5997c1bf-7bd3-402c-929d-d47d6bac7c77
Content-Type: application/json
###

# Add Category
POST {{BASE_URL}}
Content-Type: application/json

{
    "category_name": "Book"
}
###


# Update Category
PATCH {{BASE_URL}}/f7935e6f-4e89-4f7c-94e4-76d005638b1a
Content-Type: application/json

{
    "category_name": "School"
}
###


# Delete Category
DELETE {{BASE_URL}}/f7935e6f-4e89-4f7c-94e4-76d005638b1a
Content-Type: application/json
###
