@BASE_URL = http://127.0.0.1:8000/score

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk2NzAyMDg0LCJpYXQiOjE2OTY3MDExODQsImp0aSI6ImQ4YTgxYzg0ZThhODQzNzk5YWEwNTc2Y2VjZjNjODJhIiwidXNlcl9pZCI6OH0.N7_zXWEP_aAIGNjqClZC74Te9toQyK0YGjdz--kCg5M

# Add Score
POST {{BASE_URL}}-add
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "score_value":5
}

###

# Get User Score
GET {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
