@BASE_URL = http://127.0.0.1:8000/score

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk2NjcxMDI0LCJpYXQiOjE2OTY2NzAxMjQsImp0aSI6ImRhMGE0MzFmZTEzODRiNTVhZDAzZjA1MjhhOWZmY2FlIiwidXNlcl9pZCI6OX0.IzpLSvlPbGndu6rXqeoJRCIeIuu1v0qb2cdUjcRghBc

# Add Score
POST {{BASE_URL}}-add
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "score_value":11
}

###

# Get User Score
GET {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
