@BASE_URL = http://127.0.0.1:8000/score

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk2NjcyNTY2LCJpYXQiOjE2OTY2NzE2NjYsImp0aSI6IjhmMTQyODUxOGRiYTQ4ZGJiYWJhOTBiMjM0OGFhNzQzIiwidXNlcl9pZCI6MTB9.tvdEYZN3hJk9sCZHcPS-kYo6VdEfFcYtJVzE1x-KowE

# Add Score
POST {{BASE_URL}}-add
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "score_value":0
}

###

# Get User Score
GET {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
