@BASE_URL = http://127.0.0.1:8000/user

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk2NzA2NjMzLCJpYXQiOjE2OTY3MDU3MzMsImp0aSI6ImVjYTQ5YjNiZTBjZDQ5YmVhNTU2ZDkwMjRjNjM4MmUyIiwidXNlcl9pZCI6OH0.307m4V1KuwgKcBl26oJV_gbJNHKmbUo6IbTvIk4a1u8

# Register Request
POST {{BASE_URL}}/register
Content-Type: application/json

{
    "first_name":"Smikey",
    "last_name":"Bros",
    "username": "sb1",
    "email":"sb1@quiz.com",
    "password":"123456",
    "confirm_password":"123456"
}

###

# Login Request
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "username":"sb",
    "password":"123456"
}

###

# Get User Detail
GET {{BASE_URL}}/profile
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###

# Logout Request
POST {{BASE_URL}}/logout
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###