@BASE_URL = http://127.0.0.1:8000/user

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk2NjcyMjgwLCJpYXQiOjE2OTY2NzEzODAsImp0aSI6IjBhYTJmYWI2MTg1MzRlNThhYjg4NTcxMTljODEyOWFiIiwidXNlcl9pZCI6OX0.8WR7OyIBNpe-RM27tU0Db6ysm8ObPc0u0G8gIzDwbrY

# Register Request
POST {{BASE_URL}}/register
Content-Type: application/json

{
    "first_name":"Smikey",
    "last_name":"Bros",
    "username": "sb",
    "email":"sb@quiz.com",
    "password":"123456",
    "confirm_password":"123456"
}

###

# Login Request
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "username":"sb",
    "password":"123456"
}

###

# Get User Detail
GET {{BASE_URL}}/profile
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
