@BASE_URL = http://127.0.0.1:8000/user

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk2NjU5Nzc2LCJpYXQiOjE2OTY2NTg4NzYsImp0aSI6ImE0N2RhY2U2N2IyMDRmMGRhZDZiNjAxNTA4MDk3NGQwIiwidXNlcl9pZCI6N30.K2aQrgbyjh2i0W8wtERuAULIfB4knJA4_NR2OqlQGWc

# Register Request
POST {{BASE_URL}}/register
Content-Type: application/json

{
    "first_name":"Quiz",
    "last_name":"Boy",
    "username": "qb",
    "email":"user@quiz.com",
    "password":"123456",
    "confirm_password":"123456"
}

###

# Login Request
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "username":"qb",
    "password":"123456"
}

###

# Get User Detail
GET {{BASE_URL}}/profile
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
